server:
  port: 8080
spring:
  profiles:
    group:
      default: clients
      test: clients-test
      staging: clients-staging
      prod: clients-prod
  main:
    banner-mode: off
  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/fitlog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: fitlog
        password: fitlog
        pool-name: 'read-write-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/fitlog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: fitlog
        password: fitlog
        pool-name: 'read-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/fitlog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: fitlog
    password: fitlog
    locations: classpath:db/migration
jwt:
  secret-key: hidehidehidehidehidehidehidehidehide
